site_name: Kaliarch Blog
site_url: https://redhatxl.github.io/
site_author: Kaliarch
site_description: >-
  stay hungry,stay foolish

# Repository
repo_name: redhatxl.github.io
repo_url: https://github.com/redhatxl/redhatxl.github.io
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2022 kaliarch
theme:
  name: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

    # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png





# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        changelog/insiders.md: insiders/changelog.md
        reference/meta-tags.md: reference/index.md
        reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
        sponsorship.md: insiders/index.md
        upgrading.md: upgrade.md
  - minify:
      minify_html: true


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/redhatxl
    - icon: fontawesome/brands/weixin
      link: https://kaliarch-bucket-1251990360.cos.ap-beijing.myqcloud.com/blog_img/20220125122524.png
      
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/redhatxl/redhatxl.github.io/issues/new/?title=[Feedback]+{title}+-+{url}" target=_blank>feedback form</a>.
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 首页: index.md
  - 云原生:
    - 开发: 
      - cloud-native/develop/01-k8s 开发相关概念介绍.md
      - cloud-native/develop/02-K8s API 调用方式.md
      - cloud-native/develop/03-Client-go 使用.md
      - cloud-native/develop/04-Cobra + Client-go实现K8s简单插件开发.md
      - cloud-native/develop/05-client-go之ListWatcher源码分析.md
      - cloud-native/develop/06-client-go之Reflector源码分析.md
      - cloud-native/develop/07-client-go之DeltaFIFO源码分析.md
      - cloud-native/develop/08-client-go之Informer源码分析.md
      - cloud-native/develop/09-client-go之SharedInformer源码分析.md
      - cloud-native/develop/10-client-go之Indexer源码分析.md
      - cloud-native/develop/11-client-go之Workqueue源码分析.md
      - cloud-native/develop/12-自定义实现Controller.md
      - cloud-native/develop/13-认识CRD.md
      - cloud-native/develop/x-Informer实战之持久化K8s事件至ElasticSearch.md
    - 运维:
      - 工具:
        - cloud-native/operator/tools/K8s 安全之Kube-bench.md
        - cloud-native/operator/tools/kubescape安全.md
        - cloud-native/operator/tools/kubecolor.md
        - cloud-native/operator/tools/K8s 网络抓包之sniff.md
        - cloud-native/operator/tools/K8s日志查看神器之kubetail.md
        - cloud-native/operator/tools/K9s.md
        - cloud-native/operator/tools/k8s 插件管理工具之krew.md
      - 部署:
        - cloud-native/operator/deploy/最小化K8s环境之minikube.md
        - cloud-native/operator/deploy/最小化K8s环境部署之K3s.md
        - cloud-native/operator/deploy/最小化K8s环境部署之Kind.md
        - cloud-native/operator/deploy/最小化K8s环境部署之MicroK8s.md
      - servicemesh:
        - istio:
          - cloud-native/servicemesh/istio/Istio笔记之pilot.md
          - cloud-native/servicemesh/istio/Envoy笔记.md
          - cloud-native/servicemesh/istio/Istio之流量管理.md
          - cloud-native/servicemesh/istio/Istio之XDS协议解析.md

      - 排错:
        - cloud-native/operator/other/k8s 集群etcd排错.md
        - cloud-native/operator/other/CronHPA.md
        - cloud-native/operator/other/记一次K8smaster 节点一次排错实战.md
        - cloud-native/operator/other/记一次线上k8s节点维护.md
      - 容器:
        - cloud-native/容器/Dockerfile 最佳实践.md
        - cloud-native/容器/Docker底层原理.md
        - cloud-native/容器/podman详解.md
        - cloud-native/容器/利用katacoda 实现拉取国外镜像.md
        - cloud-native/容器/镜像底层原理.md
    - 其他:
      - cloud-native/other/inside-kubernetes controller.md
      - cloud-native/other/Kubectl插件开发及开业分享.md
      - cloud-native/other/KubeEdge.md
      - cloud-native/other/Kubernetes开发排错杂记.md
      - cloud-native/other/Kubernetes生成kubeconfig.md
      - cloud-native/other/华为云原生CCE实战.md
      - cloud-native/other/微服务API网关-Kong.md
      - cloud-native/other/微服务架构中10种常用设计模式.md
      
  - devops:
    - GitLab CI:
      - devops/Gitlab CI/01敏捷无敌之实战Gitlab CI.md
      - devops/Gitlab CI/02敏捷无敌之Gitlab CI架构流程详解.md
      - devops/Gitlab CI/03实战Gitlab CI + Supervisor 发布Python项目.md
      - devops/Gitlab CI/04实战前后端项目及混合环境Gitlab CI.md
      - devops/Gitlab CI/05实战Gitlab CI + Kubernetes 代码发布.md
    - IaC:
      - devops/IaC/Terraform/IaC扫描工具之Terrascan.md
      - devops/IaC/Terraform/IaC测试工具之Terratest.md
      - devops/IaC/Terraform/terraform-book.md
      - devops/IaC/Terraform/Terraform相关概念及函数.md
      - devops/IaC/Terraform/terraform最佳实践.md
    - 其他: 
      - devops/other/Argo CD.md
      - devops/other/IaC之Terraform 与Pulumi使用对比.md
      - devops/other/Packer.md
  - 开发技术:
    - 设计模式:
      - 创建型: 
        - develop/设计模式/创建型/01-golang设计模式之简单工厂模式.md
        - develop/设计模式/创建型/02-golang设计模式之工厂方法模式.md
        - develop/设计模式/创建型/03-golang设计模式之抽象工厂模式.md
        - develop/设计模式/创建型/04-golang设计模式之建造者模式.md
        - develop/设计模式/创建型/05-golang设计模式之单例模式.md
      
      - 结构型:
        - develop/设计模式/结构型/01-golang设计模式之装饰器模式.md
        - develop/设计模式/结构型/02-golang设计模式之代理模式.md
        - develop/设计模式/结构型/03-golang设计模式之桥接模式.md
        - develop/设计模式/结构型/04-golang设计模式之适配器模式.md
      - 行为型:
        - develop/设计模式/行为型/01-golang设计模式之策略模式.md
        - develop/设计模式/行为型/02-golang设计模式之观察者模式.md
        - develop/设计模式/行为型/03-golang设计模式之模版模式.md
        - develop/设计模式/行为型/04-golang设计模式之职责链模式.md
    - Golang:
      - Gin:
        - develop/Golang/gin/gin 框架实现热加载.md
        - develop/Golang/gin/gin-swagger.md
        - develop/Golang/gin/gin-validator参数校验.md
        - develop/Golang/gin/gin框架优雅关机重启.md

      - 其他:
        - develop/Golang/golang 分布式链路最终之jaeger.md
        - develop/Golang/golang 内存对齐.md
  - Linux: 
    - 系统相关:
      - linux/system/Linux grub:grub2详解.md
      - linux/system/Linux 内核引导详解.md
      - linux/system/Linux系统安全加固最佳实践.md
      - linux/system/virtio详解.md
    - Shell:
      - linux/shell/Shell简介.md
      - linux/shell/1.第一个shell程序.md
      - linux/shell/2.Shell变量.md
      - linux/shell/3.Shell参数.md
      - linux/shell/4.Shell数组.md
      - linux/shell/5.Shell运算符.md
      - linux/shell/6.Shell echo:printf命令.md
      - linux/shell/7.Shell test命令.md
      - linux/shell/8.Shell流程控制.md   
      - linux/shell/9.Shell函数.md
      - linux/shell/10.Shell输入:输出重定向.md
      - linux/shell/11.Shell 正则表达式.md
      - linux/shell/12.Shell 三剑客之grep.md
      - linux/shell/13.Shell三剑客之sed.md
      - linux/shell/14.Shell三剑客之awk.md
      - linux/shell/15.Shell常用工具.md
      - linux/shell/16.Shell实战项目.md
  - 其他:
    - 工具: other.md
    - 杂记: other.md